### ISSUE TITLE
mocking open fails

### ISSUE THREAD

**Issue by Munken** [vberlier/narmock#26]
When trying to mock the `open` system call it fails with:
```
Traceback (most recent call last):
  File "/home/munk/src/libvmemock/test/venv/bin/narmock", line 8, in <module>
    sys.exit(main())
  File "/home/munk/src/libvmemock/test/venv/lib/python3.8/site-packages/narmock/cli.py", line 44, in main
    generate_mocks(expanded_code=args.g.read(), directory=args.d, keep_args=args.k)
  File "/home/munk/src/libvmemock/test/venv/lib/python3.8/site-packages/narmock/api.py", line 15, in generate_mocks
    for function in collect_mocked_functions(expanded_code, keep_args):
  File "/home/munk/src/libvmemock/test/venv/lib/python3.8/site-packages/narmock/inspect.py", line 40, in collect_mocked_functions
    yield from ForgivingDeclarationParser(expanded_source_code, functions, keep_args)
  File "/home/munk/src/libvmemock/test/venv/lib/python3.8/site-packages/narmock/inspect.py", line 192, in __iter__
    function = self.parse_function_declaration()
  File "/home/munk/src/libvmemock/test/venv/lib/python3.8/site-packages/narmock/inspect.py", line 314, in parse_function_declaration
    else rename_arguments(file_ast.ext[-1]),
  File "/home/munk/src/libvmemock/test/venv/lib/python3.8/site-packages/narmock/inspect.py", line 53, in rename_arguments
    param_type = param.type
AttributeError: 'EllipsisParam' object has no attribute 'type'
```

Code to reproduce:
```c
#include "narwhal.h"
#include "__mocks__.h"

#include <fcntl.h>

TEST(example)
{
  MOCK(open)->mock_return(1);

  ASSERT_EQ(open("a", 0), 1);
}
```

Version of narmock:
``` 
Name: narmock
Version: 0.2.14
Summary: A minimal mocking utility for C projects.
Home-page: https://github.com/vberlier/narmock
Author: Valentin Berlier
Author-email: berlier.v@gmail.com
License: MIT
Location: /home/munk/src/libvmemock/test/venv/lib/python3.8/site-packages
Requires: pycparser, Jinja2
Required-by: 
```

**Comment by vberlier** [comment]
The problem is that `open()` is variadic and this runs into a limitation of the technique used to substitute the function with the mocked implementation. Your specific example now works in `v0.2.15` but because there's no way to forward variadic arguments transparently, I just added partial support by simply discarding the variadic part of the signature. This makes it possible to mock the function if you only call it with the fixed arguments.
